In [1]:
# Create a 1D Numpy array arr with the values [0, 1, 2, 3, 4]
# and reverse the order of the elements.


In [2]:
import random

import numpy as np

arr = np.array([0, 1, 2, 3, 4])


In [3]:
arr


array([0, 1, 2, 3, 4])

In [4]:
arr[::-1]


array([4, 3, 2, 1, 0])

In [5]:
# Create a 2D Numpy array arr with shape (3, 4) and fill it with the value 10.


In [7]:
arr = np.full((3, 4), 10)


In [8]:
arr


array([[10, 10, 10, 10],
       [10, 10, 10, 10],
       [10, 10, 10, 10]])

In [9]:
# Create a 2D Numpy array arr with shape (3, 4) and fill it
# with random values between 0 and 1.


In [11]:
arr = np.random.rand(3, 4)


In [12]:
arr


array([[0.86800705, 0.90151559, 0.56178876, 0.74144875],
       [0.92130615, 0.22350961, 0.50432585, 0.84126382],
       [0.74574091, 0.25145746, 0.8041592 , 0.08959795]])

In [13]:
# Create a 2D Numpy array arr with shape (3, 4) and
# replace all odd numbers with -1.


In [14]:
arr = np.arange(12).reshape(3, 4)


In [15]:
arr


array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [16]:
arr[arr % 2 != 0] = -1


In [17]:
arr


array([[ 0, -1,  2, -1],
       [ 4, -1,  6, -1],
       [ 8, -1, 10, -1]])

In [18]:
# Create a 1D Numpy array arr with the values [0, 1, 2, 3, 4]
# and extract the elements with indices 1 and 3.


In [19]:
arr = np.array([0, 1, 2, 3, 4])


In [20]:
arr


array([0, 1, 2, 3, 4])

In [22]:
arr[[1, 3]]


array([1, 3])

In [23]:
# Create a 2D Numpy array arr with shape (3, 4) and extract the
# elements in the first row and the last column.


In [24]:
arr = np.random.randint(0, 10, size=(3, 4))


In [25]:
arr


array([[0, 9, 0, 3],
       [1, 2, 5, 3],
       [1, 0, 7, 5]])

In [28]:
arr[0, 3]


3

In [29]:
# Create a 2D Numpy array arr with shape (3, 4) and
# extract the subarray consisting of the first two rows and the last two columns.


In [30]:
arr = np.random.randint(0, 10, size=(3, 4))


In [31]:
arr


array([[6, 0, 1, 1],
       [5, 2, 3, 5],
       [2, 0, 9, 7]])

In [37]:
arr[:2, 2:4]


array([[1, 1],
       [3, 5]])

In [38]:
# Create a 1D Numpy array arr with the values [0, 1, 2, 3, 4]
# and extract the elements greater than 2.


In [39]:
arr = np.array([0, 1, 2, 3, 4])


In [40]:
arr


array([0, 1, 2, 3, 4])

In [41]:
arr[arr > 2]


array([3, 4])

In [42]:
# Create a 2D Numpy array arr with shape (3, 4) and
# extract the elements greater than 5.


In [92]:
arr = np.random.randint(0, 10, size=(3, 4))


In [93]:
arr


array([[9, 0, 3, 4],
       [3, 4, 4, 1],
       [0, 0, 0, 0]])

In [94]:
arr[arr > 5]


array([9])

In [95]:
# Create a 2D Numpy array arr with shape (3, 4)
# and extract the elements that are even.


In [96]:
arr[(arr % 2 == 0) & (arr != 0)]


array([4, 4, 4])

In [48]:
# Create a 2D Numpy array arr with shape (3, 4) and
# replace all elements with values between 3 and 7 with -1.


In [59]:
arr = np.random.randint(0, 10, size=(3,4))


In [60]:
arr


array([[1, 5, 8, 4],
       [4, 6, 1, 8],
       [8, 0, 8, 4]])

In [61]:
arr[(arr >= 3) & (arr <= 7)] = -1


In [62]:
arr


array([[ 1, -1,  8, -1],
       [-1, -1,  1,  8],
       [ 8,  0,  8, -1]])

In [63]:
# Create a 1D Numpy array arr1 with the values [1, 2, 3]
# and a 1D Numpy array arr2 with the values [4, 5, 6].
# Combine them into a 2D Numpy array arr with shape (2, 3).


In [64]:
arr1 =np.array([1, 2, 3])


In [65]:
arr2 = np.array([4, 5, 6])


In [66]:
np.vstack([arr1, arr2])


array([[1, 2, 3],
       [4, 5, 6]])

In [67]:
# Create a 2D Numpy array arr with shape (3, 4) and transpose it.


In [68]:
arr = np.random.randint(0, 20, size=(3, 4))


In [69]:
arr


array([[ 8,  5,  6,  4],
       [17,  3, 15,  2],
       [ 0,  6,  1,  6]])

In [70]:
arr.T


array([[ 8, 17,  0],
       [ 5,  3,  6],
       [ 6, 15,  1],
       [ 4,  2,  6]])

In [71]:
# Create a 2D Numpy array arr with shape (3, 4) and swap its axes.


In [72]:
arr = np.random.randint(0, 25, size=(3, 4))


In [73]:
arr


array([[22,  6,  6,  5],
       [ 5, 15,  8, 21],
       [17, 11, 12, 11]])

In [75]:
arr.swapaxes(0, 1)


array([[22,  5, 17],
       [ 6, 15, 11],
       [ 6,  8, 12],
       [ 5, 21, 11]])

In [76]:
# Create a 2D Numpy array arr1 with shape (3, 4) and
# a 2D Numpy array arr2 with shape (4, 3).
# Compute the dot product of the two arrays.


In [77]:
arr1 = np.random.randint(15, 25, size=(3, 4))


In [78]:
arr1


array([[17, 21, 20, 17],
       [21, 21, 22, 23],
       [23, 16, 15, 22]])

In [79]:
arr2 = np.random.randint(0, 10, size=(4, 3))


In [80]:
arr2


array([[5, 8, 8],
       [3, 8, 2],
       [6, 6, 0],
       [0, 4, 2]])

In [81]:
np.dot(arr1, arr2)


array([[268, 492, 212],
       [300, 560, 256],
       [253, 490, 260]])

In [82]:
# Create a 3D Numpy array arr with shape (4, 3, 5) and
# use fancy indexing to extract all elements where the sum of the indices is odd.


In [97]:
arr = np.random.randint(10, 55, size=(4, 3, 5))


In [98]:
arr


array([[[18, 17, 38, 37, 18],
        [32, 14, 44, 34, 12],
        [31, 23, 39, 28, 15]],

       [[11, 35, 46, 46, 10],
        [17, 34, 10, 45, 43],
        [33, 22, 43, 31, 15]],

       [[38, 49, 38, 32, 17],
        [16, 35, 12, 11, 46],
        [29, 36, 38, 27, 37]],

       [[20, 30, 44, 18, 21],
        [21, 28, 15, 52, 35],
        [47, 23, 38, 22, 27]]])

In [99]:
arr[np.sum(np.indices(arr.shape), axis=0) % 2 != 0]


array([17, 37, 32, 44, 12, 23, 28, 11, 46, 10, 34, 45, 33, 43, 15, 49, 32,
       16, 12, 46, 36, 27, 20, 44, 21, 28, 52, 47, 38, 27])

In [100]:
# Create a 2D Numpy array arr with shape (5, 6) and
# use fancy indexing to extract all elements that are multiples of 3.


In [101]:
arr = np.random.randint(12, 63, size=(5, 6))


In [102]:
arr


array([[28, 32, 41, 18, 49, 32],
       [15, 21, 38, 14, 16, 55],
       [30, 13, 57, 45, 32, 26],
       [50, 18, 15, 23, 55, 41],
       [59, 14, 24, 29, 41, 60]])

In [103]:
arr[(arr % 3 == 0)]


array([18, 15, 21, 30, 57, 45, 18, 15, 24, 60])

In [104]:
# Create a 2D Numpy array arr with shape (4, 5) and use fancy
# indexing to extract the elements in the second and fourth
# columns that are greater than 5.


In [113]:
arr = np.random.randint(0, 10, size=(4, 5))


In [114]:
arr


array([[3, 0, 7, 3, 6],
       [2, 6, 2, 9, 2],
       [9, 0, 1, 8, 2],
       [2, 1, 9, 3, 8]])

In [115]:
arr_sub = arr[:, (-2, -1)]


In [116]:
arr_sub


array([[3, 6],
       [9, 2],
       [8, 2],
       [3, 8]])

In [117]:
arr_sub[arr_sub > 5]


array([6, 9, 8, 8])

In [112]:
# Create a 2D Numpy array arr with shape (5, 5)
# and use slicing to extract a subarray with a diagonal
# of ones and zeros elsewhere.


In [122]:
arr = np.zeros((5, 5))


In [123]:
arr


array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [124]:
arr[np.diag_indices(5)] = 1


In [125]:
arr


array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [126]:
# Create a 2D Numpy array arr with shape (5, 6)
# and use fancy indexing to extract all elements
# that are not divisible by 2, 3, or 5.


In [127]:
arr = np.random.randint(1, 53, size=(5, 6))


In [128]:
arr

array([[ 1,  2, 43, 12, 19, 23],
       [31,  9,  9,  1, 15, 29],
       [12, 27,  9, 46,  6, 14],
       [ 5, 13, 12, 31, 32, 35],
       [10, 29,  8, 11,  3,  2]])

In [129]:
arr[(arr % 2 != 0) & (arr % 3 != 0) & (arr % 5 != 0)]


array([ 1, 43, 19, 23, 31,  1, 29, 13, 31, 29, 11])

In [130]:
# Create a 2D Numpy array arr with shape (6, 6) and use
# transposing and fancy indexing to extract the elements
# on the main diagonal and the anti-diagonal.


In [131]:
arr = np.random.randint(1, 67, size=(6, 6))


In [132]:
arr


array([[45, 43, 22, 58,  2, 42],
       [ 2, 26,  9, 16, 22, 29],
       [ 7, 57, 14,  9, 56, 36],
       [10, 17,  2,  8, 49, 33],
       [36, 16, 66, 45, 24, 17],
       [26, 40, 17, 61, 64, 43]])

In [133]:
arr[np.diag_indices(6)]


array([45, 26, 14,  8, 24, 43])

In [134]:
np.diag(np.fliplr(arr))


array([42, 22,  9,  2, 16, 26])

In [135]:
np.append(arr[np.diag_indices(6)], np.diag(np.fliplr(arr)))


array([45, 26, 14,  8, 24, 43, 42, 22,  9,  2, 16, 26])

In [136]:
# Create a 3D Numpy array arr with shape (3, 4, 5)
# and use fancy indexing to extract all elements where the
# second index is greater than the first index.


In [143]:
arr = np.random.randint(1, 49, size=(3, 4, 5))


In [144]:
arr


array([[[17,  2,  2, 38, 15],
        [16,  3, 48, 19, 41],
        [31, 47, 32, 35, 10],
        [17, 30, 18, 32, 12]],

       [[ 7, 11, 45, 44, 43],
        [13, 30, 15, 48, 27],
        [47, 39, 28, 48, 13],
        [39, 39, 30,  8, 13]],

       [[48, 13, 48, 38, 18],
        [ 6, 34, 44, 37, 44],
        [ 7, 12, 11, 20, 22],
        [ 6, 40, 22, 15, 22]]])

In [157]:
arr1 = arr[:, :, -4]


In [158]:
arr1


array([[ 2,  3, 47, 30],
       [11, 30, 39, 39],
       [13, 34, 12, 40]])

In [159]:
arr2 = arr[:, :, -5]


In [160]:
arr2


array([[17, 16, 31, 17],
       [ 7, 13, 47, 39],
       [48,  6,  7,  6]])

In [161]:
arr[arr1 > arr2]


array([[31, 47, 32, 35, 10],
       [17, 30, 18, 32, 12],
       [ 7, 11, 45, 44, 43],
       [13, 30, 15, 48, 27],
       [ 6, 34, 44, 37, 44],
       [ 7, 12, 11, 20, 22],
       [ 6, 40, 22, 15, 22]])

In [162]:
# Create a 2D Numpy array arr with shape (6, 6) and
# use slicing and fancy indexing to extract the elements
# in the first and last rows and columns.


In [163]:
arr = np.random.randint(23, 71, size=(6, 6))


In [164]:
arr


array([[61, 52, 70, 48, 26, 63],
       [60, 56, 47, 34, 56, 68],
       [65, 48, 25, 39, 55, 49],
       [27, 54, 58, 47, 41, 41],
       [24, 49, 57, 67, 29, 55],
       [52, 56, 59, 56, 38, 25]])

In [174]:
arr_frow_lcol = arr[(0, -1), :]


In [175]:
arr_frow_lcol


array([[61, 52, 70, 48, 26, 63],
       [52, 56, 59, 56, 38, 25]])

In [176]:
# Create a 2D Numpy array arr with shape (5, 5) and use boolean
# indexing to extract all elements that are either less than 3 or greater than 7.


In [179]:
arr = np.random.randint(0, 10, size=(5, 5))


In [180]:
arr


array([[3, 8, 3, 5, 9],
       [6, 9, 9, 4, 1],
       [5, 2, 7, 1, 2],
       [9, 4, 0, 4, 9],
       [2, 2, 1, 2, 1]])

In [184]:
arr1 = arr[(arr < 3) | (arr > 7)]


In [185]:
arr1


array([8, 9, 9, 9, 1, 2, 1, 2, 9, 0, 9, 2, 2, 1, 2, 1])

In [188]:
# Create a 2D Numpy array arr with shape (6, 6) and
# use transposing and slicing to extract the elements
# in the first row, last column, and the diagonal from the
# upper left to the lower right.


In [189]:
arr = np.random.randint(23, 67, size=(6, 6))


In [190]:
arr


array([[50, 63, 56, 37, 55, 37],
       [54, 63, 62, 43, 60, 47],
       [45, 23, 61, 35, 40, 47],
       [48, 64, 50, 55, 38, 34],
       [34, 32, 56, 66, 43, 33],
       [24, 37, 47, 61, 47, 44]])

In [192]:
arr_frow_lcol = arr[(0, -1), :]


In [193]:
arr_frow_lcol


array([[50, 63, 56, 37, 55, 37],
       [24, 37, 47, 61, 47, 44]])

In [194]:
diag_lr = np.diag(arr)


In [195]:
diag_lr


array([50, 63, 61, 55, 43, 44])

In [196]:
diag_rl = np.diag(np.fliplr(arr))


In [197]:
diag_rl


array([37, 60, 35, 50, 32, 24])

In [198]:
# Create a 3D Numpy array arr with shape (4, 3, 5) and
# compute the product of each 3x5 matrix along the first axis.


In [199]:
arr =np.random.randint(13, 57, size=(4, 3, 5))


In [200]:
arr


array([[[22, 36, 47, 36, 43],
        [28, 33, 56, 20, 45],
        [53, 40, 53, 36, 20]],

       [[45, 39, 34, 16, 45],
        [24, 54, 39, 24, 16],
        [25, 46, 47, 33, 34]],

       [[42, 45, 17, 33, 51],
        [32, 13, 55, 32, 35],
        [56, 26, 22, 23, 13]],

       [[42, 14, 35, 34, 35],
        [37, 15, 19, 16, 13],
        [42, 33, 31, 53, 24]]])

In [201]:
np.prod(arr, axis=0)


array([[1746360,  884520,  950810,  646272, 3453975],
       [ 795648,  347490, 2282280,  245760,  327600],
       [3116400, 1578720, 1698862, 1448172,  212160]])

In [202]:
# Create a 2D Numpy array arr with shape (5, 6) and
# compute the mean of each row after subtracting the row mean from each element.


In [203]:
arr =np.random.randint(21, 69, size=(5, 6))


In [204]:
arr


array([[62, 37, 57, 24, 54, 45],
       [50, 56, 62, 51, 49, 67],
       [58, 26, 26, 23, 22, 34],
       [21, 55, 47, 22, 66, 35],
       [57, 37, 46, 32, 58, 36]])

In [205]:
mean_row = arr.mean(axis=1, keepdims=True)


In [206]:
(arr - mean_row).mean(axis=1)


array([ 0.00000000e+00, -2.36847579e-15,  0.00000000e+00,  0.00000000e+00,
       -2.36847579e-15])

In [207]:
# Create two 2D Numpy arrays A and B with shapes (3, 4) and (4, 5),
# respectively, and compute the matrix product A @ B.


In [208]:
A = np.random.randint(0, 10, size=(3, 4))


In [209]:
A


array([[0, 5, 3, 5],
       [6, 7, 0, 1],
       [2, 4, 7, 4]])

In [210]:
B = np.random.randint(0, 10, size=(4, 5))


In [211]:
B


array([[7, 5, 8, 7, 6],
       [5, 8, 9, 0, 6],
       [0, 2, 1, 4, 8],
       [8, 1, 1, 9, 7]])

In [212]:
A @ B


array([[ 65,  51,  53,  57,  89],
       [ 85,  87, 112,  51,  85],
       [ 66,  60,  63,  78, 120]])

In [213]:
# Create a 2D Numpy array arr with shape (5, 6) and
# compute the sum of the absolute differences between
# each element and its four nearest neighbors (up, down, left, and right),
# ignoring boundary elements.


In [214]:
arr = np.random.randint(0, 10, size=(5, 6))


In [215]:
arr


array([[0, 3, 9, 8, 3, 8],
       [8, 6, 6, 9, 9, 8],
       [2, 6, 4, 5, 3, 2],
       [0, 5, 3, 4, 2, 1],
       [0, 4, 4, 9, 2, 9]])

In [225]:
arr[1:-1, 1:-1]


array([[6, 6, 9, 9],
       [6, 4, 5, 3],
       [5, 3, 4, 2]])

In [226]:
arr[:-2, 1:-1]


array([[3, 9, 8, 3],
       [6, 6, 9, 9],
       [6, 4, 5, 3]])

In [227]:
arr[2:, 1:-1]


array([[6, 4, 5, 3],
       [5, 3, 4, 2],
       [4, 4, 9, 2]])

In [228]:
arr[1:-1, :-2]


array([[8, 6, 6, 9],
       [2, 6, 4, 5],
       [0, 5, 3, 4]])

In [229]:
arr[1:-1, 2:]


array([[6, 9, 9, 8],
       [4, 5, 3, 2],
       [3, 4, 2, 1]])

In [232]:
np.sum(np.abs((arr[1:-1, 1:-1]) - (arr[:-2, 1:-1] + arr[2:, 1:-1] + arr[1:-1, :-2] + arr[1:-1, 2:])))


174

In [233]:
arr

array([[0, 3, 9, 8, 3, 8],
       [8, 6, 6, 9, 9, 8],
       [2, 6, 4, 5, 3, 2],
       [0, 5, 3, 4, 2, 1],
       [0, 4, 4, 9, 2, 9]])