In [ ]:
# Create a NumPy array with the numbers 1 to 10.


In [2]:
import numpy as np


In [3]:
my_array = np.arange(1, 11)


In [4]:
my_array


array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [5]:
# Create a NumPy array with 10 zeros.


In [6]:
np.zeros(10)


array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [9]:
# Create a NumPy array with 10 ones.


In [10]:
np.ones(10)


array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [11]:
# Create a 2D NumPy array with the numbers 1 to 9, with 3 rows and 3 columns.


In [12]:
arr2d = np.arange(1, 10).reshape(3, 3)


In [13]:
arr2d


array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [14]:
# Create a 2D NumPy array with the numbers 0 to 8,
# with 3 rows and 3 columns.


In [16]:
arr2d_2 = np.arange(9).reshape(3, 3)


In [17]:
arr2d_2


array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [18]:
# Create a 3D NumPy array with shape (2, 3, 4)
# with random integers between 0 and 9.


In [19]:
import random


In [20]:
arr3d = np.random.randint(0, 10, size=(2, 3, 4))


In [21]:
arr3d


array([[[1, 0, 5, 6],
        [2, 2, 8, 0],
        [0, 3, 7, 0]],

       [[3, 0, 6, 4],
        [3, 8, 2, 3],
        [3, 0, 6, 8]]])

In [22]:
# Create a 2D NumPy array with shape (3, 3) and fill it with a
# sequence of numbers from 0 to 8.


In [23]:
arr2d_3 = np.arange(9).reshape(3, 3)


In [24]:
arr2d_3


array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [25]:
# Create a 1D NumPy array with shape (10,) and fill it with random
# integers between 0 and 99.


In [27]:
arr_1d = np.random.randint(0, 100, size=10)


In [28]:
arr_1d


array([52, 13, 74,  7,  6, 88, 66, 55, 31, 15])

In [29]:
# Create a 2D NumPy array with shape (4, 4)
# and fill it with random integers between


In [88]:
arr_2d_4 = np.arange(16, 32).reshape(4, 4)


In [89]:
arr_2d_4


array([[16, 17, 18, 19],
       [20, 21, 22, 23],
       [24, 25, 26, 27],
       [28, 29, 30, 31]])

In [90]:
sub_arr_2d_4 = np.random.randint(-1, arr_2d_4[0:4, (1, 3)])

In [91]:
sub_arr_2d_4


array([[11,  3],
       [ 6,  8],
       [22, 23],
       [22,  2]])

In [93]:
arr_2d_4[0:4, (1, 3)] = sub_arr_2d_4


In [94]:
arr_2d_4


array([[16, 11, 18,  3],
       [20,  6, 22,  8],
       [24, 22, 26, 23],
       [28, 22, 30,  2]])

In [95]:
# Create a 3D NumPy array with shape (2, 4, 4) and
# fill it with random integers between 1 and 10,
# then extract a subarray consisting of the first row of the first 2 matrices.


In [96]:
arr3d_2 = np.random.randint(1, 10, size=(2, 4, 4))


In [97]:
arr3d_2


array([[[1, 1, 6, 3],
        [5, 6, 6, 1],
        [6, 7, 4, 2],
        [1, 1, 7, 1]],

       [[6, 1, 6, 5],
        [8, 8, 3, 6],
        [6, 6, 3, 5],
        [8, 1, 6, 7]]])

In [103]:
sub_arr3d_2 = arr3d_2[:, 0]


In [104]:
sub_arr3d_2


array([[1, 1, 6, 3],
       [6, 1, 6, 5]])

In [105]:
# Create a 2D NumPy array with shape (3, 4) and fill it with
# random floats between 0 and 1.


In [115]:
arr2d_6 = np.random.random(size=(3, 4))


In [116]:
arr2d_6


array([[0.08010878, 0.56884195, 0.58993818, 0.60032421],
       [0.60336296, 0.87575487, 0.25694044, 0.77535927],
       [0.43726851, 0.47304115, 0.84199494, 0.93869423]])

In [117]:
# Create a 2D NumPy array with shape (3, 3) and fill it with the
# numbers 1 to 9, then transpose the array.


In [118]:
arr2d_7 = np.arange(1, 10).reshape(3, 3)


In [119]:
arr2d_7


array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [120]:
arr2d_7_T = arr2d_7.T


In [121]:
arr2d_7_T


array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [122]:
# Create a 2D NumPy array with shape (4, 4) and fill it with
# random integers between -5 and 5, then extract a subarray
# consisting of the last 3 rows and the first 2 columns.


In [123]:
arr2d_8 = np.random.randint(-5, 6, size=(4, 4))


In [124]:
arr2d_8


array([[ 4, -5,  3, -5],
       [ 3,  2, -5, -3],
       [ 4,  2, -2,  1],
       [-1,  3, -4, -5]])

In [130]:
sub_arr2d_8 = arr2d_8[1:, 0:2]


In [131]:
sub_arr2d_8


array([[ 3,  2],
       [ 4,  2],
       [-1,  3]])

In [132]:
# Create a 2D NumPy array with shape (5, 5) and fill it
# with a checkerboard pattern of 0's and 1's.


In [133]:
arr2d = np.zeros(shape=(5, 5))


In [134]:
arr2d


array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [139]:
arr2d[1::2, ::2] = 1


In [140]:
arr2d


array([[0., 0., 0., 0., 0.],
       [1., 0., 1., 0., 1.],
       [0., 0., 0., 0., 0.],
       [1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1.]])

In [141]:
arr2d[::2, 1::2] = 1


In [142]:
arr2d


array([[0., 1., 0., 1., 0.],
       [1., 0., 1., 0., 1.],
       [0., 1., 0., 1., 0.],
       [1., 0., 1., 0., 1.],
       [1., 1., 1., 1., 1.]])

In [143]:
# Create a 1D NumPy array of length 100 and reshape it into a 10x10 grid.


In [144]:
my_array = np.arange(100).reshape(10, 10)


In [145]:
my_array


array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [146]:
# Create a 2D NumPy array with shape (3, 3) and fill it with
# random integers between 0 and 9. Replace all values greater than 5 with the value 5.


In [147]:
my_array = np.random.randint(0, 9, size=(3, 3))


In [148]:
my_array


array([[3, 8, 5],
       [0, 1, 6],
       [7, 1, 4]])

In [149]:
my_array[my_array > 5] = 5


In [150]:
my_array


array([[3, 5, 5],
       [0, 1, 5],
       [5, 1, 4]])

In [151]:
# Create a 1D NumPy array of length 10 and fill it with random
# integers between 0 and 9. Find the index of the maximum value in the array.


In [158]:
my_array = np.random.randint(0, 9, size=10)


In [159]:
my_array


array([4, 1, 2, 8, 3, 7, 5, 6, 6, 0])

In [163]:
np.argmax(my_array)


3

In [164]:
# Create a 2D NumPy array with shape (3, 4) and fill it with random
# integers between 0 and 9. Create a new array that contains
# only the even numbers from the original array.

In [165]:
my_array = np.random.randint(0, 9, size=(3, 4))


In [166]:
my_array


array([[7, 7, 4, 2],
       [6, 4, 1, 3],
       [5, 4, 7, 1]])

In [167]:
my_array2 = my_array[my_array % 2 == 0]


In [168]:
my_array2


array([4, 2, 6, 4, 4])

In [169]:
# Create a 2D NumPy array with shape (3, 3) and fill it with
# random integers between 5 and 9. Replace all values that are
# less than the minimum value in the array with the minimum value,
# and all values that are greater than the maximum value in the array
# with the maximum value.


In [198]:
my_array = np.random.randint(0, 10, size=(3, 3))


In [199]:
my_array


array([[9, 1, 1],
       [2, 5, 1],
       [5, 1, 6]])

In [200]:
min_value = np.min(my_array)


In [201]:
max_value = np.max(my_array)


In [202]:
my_array[my_array < min_value] = min_value


In [203]:
my_array[my_array > max_value] = max_value


In [204]:
my_array


array([[9, 1, 1],
       [2, 5, 1],
       [5, 1, 6]])

In [205]:
# Create a 3D NumPy array with shape (2, 3, 4) and
# fill it with random integers between 0 and 9.
# Compute the sum of all elements in the array.


In [206]:
my_array = np.random.randint(0, 10, size=(2, 3, 4))


In [207]:
my_array


array([[[4, 0, 6, 0],
        [0, 4, 6, 3],
        [5, 9, 8, 4]],

       [[0, 5, 9, 3],
        [3, 2, 8, 7],
        [9, 0, 2, 9]]])

In [208]:
np.sum(my_array)


106

In [209]:
# Create a 2D NumPy array with shape (5, 5) and fill it with
# random integers between 0 and 9. Create a new array that
# contains only the values in the top-left quadrant of the original array.


In [210]:
my_array = np.random.randint(0, 10, size=(5, 5))


In [211]:
my_array


array([[1, 3, 4, 2, 2],
       [7, 4, 2, 8, 9],
       [8, 2, 0, 3, 3],
       [5, 9, 5, 3, 9],
       [0, 4, 1, 1, 9]])

In [214]:
my_array[:3, :3]


array([[1, 3, 4],
       [7, 4, 2],
       [8, 2, 0]])

In [215]:
# Create a 2D NumPy array with shape (4, 4) and fill it with
# random integers between -5 and 5.
# Find the indices of all values that are greater than or equal to 0.


In [216]:
my_array = np.random.randint(-5, 6, size=(4, 4))


In [217]:
my_array


array([[ 4, -2,  1,  5],
       [ 4, -4,  2,  4],
       [-5, -1, -2,  5],
       [-4, -2,  5,  3]])

In [219]:
np.argwhere(my_array >= 0)


array([[0, 0],
       [0, 2],
       [0, 3],
       [1, 0],
       [1, 2],
       [1, 3],
       [2, 3],
       [3, 2],
       [3, 3]], dtype=int64)