In [1]:
# Generate a random integer between 0 and 10 using the
# numpy.random.randint function.


In [2]:
import numpy as np
import random


In [3]:
num_int = np.random.randint(0, 11)


In [4]:
num_int


4

In [5]:
# Generate a 3x3 array of random integers between
# 0 and 10 using the numpy.random.randint function.


In [6]:
arr = np.random.randint(0, 11, size=(3, 3))


In [7]:
arr


array([[2, 3, 0],
       [0, 6, 1],
       [1, 3, 6]])

In [8]:
# Generate a random float between 0 and 1 using the numpy.random.random function.


In [11]:
arr = np.random.random()


In [12]:
arr


0.5579317294693182

In [13]:
# Generate a 3x3 array of random floats between 0 and 1
# using the numpy.random.random function.


In [14]:
arr = np.random.random((3, 3))


In [15]:
arr


array([[0.09079298, 0.41016595, 0.09269702],
       [0.12613745, 0.70092616, 0.58137517],
       [0.22862903, 0.14383972, 0.59487667]])

In [16]:
# Generate a random integer between 0 and 10 using the numpy.random.choice function.


In [17]:
arr = np.random.choice(11)


In [18]:
arr


1

In [19]:
# Generate a 3x3 array of random integers between 0 and 10 using
# the numpy.random.choice function.


In [21]:
arr = np.random.choice(11, size=(3, 3))


In [22]:
arr


array([[ 5,  4,  1],
       [ 8,  3, 10],
       [ 5,  5,  8]])

In [23]:
# Generate an array of 10 random numbers from a
# normal distribution with mean 0 and standard
# deviation 1 using the numpy.random.normal function.


In [24]:
arr = np.random.normal(0, 1, size=10)


In [25]:
arr


array([-0.06638424, -0.97089569,  1.29120286, -0.73495072, -1.02687644,
       -0.47255144,  1.38638153, -0.79281309, -1.35033249,  0.19158006])

In [26]:
# Generate an array of 10 random numbers from a uniform
# distribution between 0 and 1 using the numpy.random.uniform function.


In [27]:
arr = np.random.uniform(0, 1, size=10)


In [28]:
arr


array([0.26530463, 0.48152691, 0.9680236 , 0.41414309, 0.47211439,
       0.31069421, 0.4532829 , 0.9114635 , 0.39487466, 0.10303302])

In [29]:
# Generate an array of 10 random numbers from a exponential
# distribution with a rate of 0.5 using the
# numpy.random.exponential function.


In [30]:
arr = np.random.exponential(scale=1/0.5, size=10)


In [31]:
arr


array([0.90158301, 1.95754679, 1.00924983, 2.68329309, 0.25564557,
       3.52784098, 4.09300005, 3.61038436, 1.55483628, 7.24885773])

In [32]:
# Generate an array of 10 random numbers from a
# Poisson distribution with a lambda of 2 using the
# numpy.random.poisson function.


In [33]:
arr = np.random.poisson(lam=2, size=10)


In [34]:
arr


array([0, 0, 2, 6, 2, 1, 3, 1, 5, 0])

In [35]:
# Write a NumPy program to generate a random 2D array of size 3x3.


In [42]:
arr = np.random.rand(3, 3)


In [43]:
arr


array([[0.97674125, 0.95806919, 0.47041408],
       [0.0374432 , 0.14863851, 0.26368395],
       [0.80535171, 0.6977857 , 0.81931119]])

In [44]:
# Write a NumPy program to generate 5 random integers
# between 1 and 10 (inclusive).


In [45]:
arr = np.random.randint(1, 11, size=5)


In [46]:
arr


array([ 1,  7,  9,  8, 10])

In [47]:
# Write a NumPy program to generate 10 random values
# from a normal distribution with a mean of 0 and a
# standard deviation of 1.


In [48]:
arr = np.random.normal(0, 1, size=10)


In [49]:
arr


array([-0.89703379, -0.07323891,  1.23418474,  1.14733124,  0.85841942,
        1.24375856, -1.17448106,  0.42083651,  1.0740503 ,  0.49781   ])

In [50]:
# Write a NumPy program to generate a random permutation of a given 1D array.


In [51]:
arr = np.random.randint(13, 47, size=5)


In [52]:
arr


array([46, 40, 17, 39, 41])

In [53]:
perm_arr = np.random.permutation(arr)


In [54]:
perm_arr


array([17, 41, 40, 46, 39])

In [55]:
# Write a NumPy program to generate a 5x5 array of random boolean values.


In [56]:
arr = np.random.choice([True, False], size=(5, 5))


In [57]:
arr


array([[ True,  True, False,  True,  True],
       [ True, False,  True,  True,  True],
       [ True, False,  True,  True, False],
       [ True,  True,  True, False, False],
       [ True, False,  True, False, False]])

In [58]:
# Write a NumPy program to generate a 1D array of 10
# random numbers between 0 and 1, and then replace all
# values greater than 0.5 with 1.


In [59]:
arr = np.random.random(10)


In [60]:
arr


array([0.55424112, 0.12082789, 0.85162022, 0.15691147, 0.10260563,
       0.5311238 , 0.84125386, 0.45937415, 0.94603101, 0.98525706])

In [61]:
arr[arr > 0.5] = 1


In [62]:
arr


array([1.        , 0.12082789, 1.        , 0.15691147, 0.10260563,
       1.        , 1.        , 0.45937415, 1.        , 1.        ])

In [63]:
# Write a NumPy program to generate a 2D array of size 5x5
# with random values between 0 and 1, and then normalize
# each row to have unit length.


In [65]:
arr = np.random.random((5, 5))


In [66]:
arr


array([[0.26736971, 0.04887781, 0.25231355, 0.43447091, 0.06872107],
       [0.95157029, 0.66821342, 0.62958755, 0.72696876, 0.32667771],
       [0.36062406, 0.48673555, 0.54759143, 0.93282428, 0.92136077],
       [0.56653375, 0.23982486, 0.16549674, 0.5877848 , 0.17684039],
       [0.96141957, 0.86625395, 0.0965538 , 0.08242828, 0.4400397 ]])

In [67]:
arr_norm = np.apply_along_axis(lambda row: row / np.linalg.norm(row), axis=1, arr=arr)


In [68]:
arr_norm


array([[0.46470958, 0.08495348, 0.43854078, 0.7551446 , 0.11944262],
       [0.61634834, 0.43281325, 0.40779461, 0.47087009, 0.21159474],
       [0.23346942, 0.31511449, 0.35451282, 0.60391407, 0.59649254],
       [0.64039478, 0.27109169, 0.18707314, 0.66441641, 0.1998957 ],
       [0.70035416, 0.63102996, 0.07033543, 0.06004558, 0.32055061]])

In [69]:
# Write a NumPy program to generate a 1D array of 10
# random integers between 1 and 100, and then find the
# median of the array.


In [70]:
arr = np.random.randint(1, 101, size=10)


In [71]:
arr


array([11, 25, 10, 98, 33,  3, 47, 41, 64, 31])

In [72]:
arr_median = np.median(arr)


In [73]:
arr_median

32.0

In [74]:
# Write a NumPy program to generate a 2D array of size
# 3x3 with random values between 0 and 1, and then sort
# the values in each row.


In [75]:
arr = np.random.random((3, 3))


In [76]:
arr


array([[0.97239148, 0.85382176, 0.72915439],
       [0.59861821, 0.9514444 , 0.03339915],
       [0.09464795, 0.32850153, 0.25107265]])

In [77]:
arr_sorted = np.sort(arr, axis=1)


In [78]:
arr_sorted


array([[0.72915439, 0.85382176, 0.97239148],
       [0.03339915, 0.59861821, 0.9514444 ],
       [0.09464795, 0.25107265, 0.32850153]])

In [79]:
# Write a NumPy program to generate a 1D array of
# 10 random integers between 1 and 100, and then find
# the top 3 values in the array.


In [80]:
arr = np.random.randint(1, 101, size=10)


In [81]:
arr


array([19, 17, 73, 87, 38, 95, 42, 48, 14, 58])

In [85]:
arr_sorted = np.sort(arr)


In [86]:
arr_sorted


array([14, 17, 19, 38, 42, 48, 58, 73, 87, 95])

In [89]:
arr_sorted[(10-3):(10 + 1)]


array([73, 87, 95])

In [90]:
# Generate a 2-dimensional array of size (5,5) with random
# numbers from a normal distribution with mean 0 and
# standard deviation 1.


In [91]:
arr = np.random.normal(0, 1, size=(5, 5))


In [92]:
arr


array([[-0.22813162,  1.14243978, -0.45802586,  0.83386676,  0.87865205],
       [-0.02269081, -0.73694883, -0.08245337, -0.51130905, -0.1255313 ],
       [ 0.87126175, -0.53837923,  0.95329006, -2.13384412, -0.79794193],
       [-0.21306254, -1.38519399,  1.21125692, -0.18611228, -0.91061577],
       [ 0.10216772,  0.70211891, -0.25992101, -0.99181102, -1.14590679]])

In [93]:
# Generate an array of size (100, 100) with random integers
# between 0 and 9, inclusive.


In [94]:
arr = np.random.randint(0, 10, size=(100, 100))


In [95]:
arr


array([[5, 4, 2, ..., 5, 1, 1],
       [9, 5, 9, ..., 6, 8, 4],
       [4, 7, 5, ..., 3, 8, 1],
       ...,
       [6, 1, 1, ..., 0, 3, 0],
       [2, 5, 5, ..., 1, 5, 6],
       [8, 4, 9, ..., 3, 2, 6]])

In [96]:
# Generate an array of size (3,3) with random numbers from a
# uniform distribution between 0 and 1, and then round the numbers
# to the nearest 0.1.


In [97]:
arr = np.random.uniform(0, 1, size=(3, 3))


In [98]:
arr


array([[0.02889574, 0.06776591, 0.11897457],
       [0.81121105, 0.30989544, 0.87431971],
       [0.76546223, 0.93390386, 0.85305263]])

In [102]:
np.round(arr, 1)


array([[0. , 0.1, 0.1],
       [0.8, 0.3, 0.9],
       [0.8, 0.9, 0.9]])

In [103]:
# Generate an array of size (4,4) with random
# numbers from a Poisson distribution with a lambda value of 2.


In [104]:
arr = np.random.poisson(lam=2, size=(4, 4))


In [105]:
arr


array([[3, 0, 2, 2],
       [0, 1, 0, 3],
       [4, 3, 0, 2],
       [2, 2, 3, 3]])

In [106]:
# Generate an array of size (5,5) with random numbers
# from a geometric distribution with a p-value of 0.2.


In [107]:
arr = np.random.geometric(0.2, size=(5, 5))


In [108]:
arr


array([[ 6,  4,  4,  1,  2],
       [ 2,  2,  2,  3,  4],
       [ 5,  6,  6,  4,  4],
       [ 6,  9,  1,  1,  1],
       [ 4, 25,  1,  2,  2]])

In [109]:
# Generate an array of size (5,5) with random
# numbers from a binomial distribution with n=10 and p=0.3.


In [110]:
arr = np.random.binomial(10, 0.3, size=(5, 5))


In [111]:
arr


array([[3, 1, 5, 4, 5],
       [5, 2, 3, 3, 1],
       [6, 1, 3, 3, 1],
       [2, 4, 1, 2, 4],
       [2, 2, 4, 4, 3]])

In [112]:
# Generate a random permutation of the numbers 1 through 10.


In [121]:
arr = np.random.permutation(11)


In [122]:
arr


array([ 4,  1,  6, 10,  8,  9,  2,  7,  5,  0,  3])

In [123]:
# Generate an array of size (3,3) with random numbers from a
# beta distribution with alpha=2 and beta=5.


In [124]:
arr = np.random.beta(2, 5, size=(3, 3))


In [125]:
arr


array([[0.08908845, 0.48854567, 0.17293696],
       [0.24758009, 0.24978495, 0.50801326],
       [0.52147829, 0.15283714, 0.11129573]])

In [126]:
# Generate an array of size (4,4) with random numbers from a
# Laplace distribution with mean 0 and scale 1.


In [127]:
arr = np.random.laplace(0, 1, size=(4, 4))


In [128]:
arr


array([[-0.24199268,  0.49873988,  1.43739679,  0.1458479 ],
       [ 3.23566702,  1.10003923,  0.05368416, -0.60533944],
       [ 0.38726801, -0.30464632, -1.16547488,  0.02418361],
       [ 0.06697766, -0.38663971, -0.20063332,  0.41112238]])

In [129]:
# Generate an array of size (5,5) with random numbers from a
# standard normal distribution and replace any negative numbers with 0.


In [130]:
arr = np.random.normal(size=(5, 5))


In [131]:
arr


array([[ 1.2759312 ,  0.33836627,  0.10658203,  0.74545628, -1.41059548],
       [ 0.31769267, -1.04778973,  1.3870758 ,  0.88731724, -0.14774108],
       [ 0.57071797, -0.2529751 , -1.05625441, -1.41337671, -0.05645494],
       [ 1.20345207, -1.23408536, -0.91360178,  0.85485093,  1.12201383],
       [ 0.26547767, -0.68662441, -0.50536264, -0.07130083,  0.11027878]])

In [132]:
arr[arr < 0] = 0


In [133]:
arr


array([[1.2759312 , 0.33836627, 0.10658203, 0.74545628, 0.        ],
       [0.31769267, 0.        , 1.3870758 , 0.88731724, 0.        ],
       [0.57071797, 0.        , 0.        , 0.        , 0.        ],
       [1.20345207, 0.        , 0.        , 0.85485093, 1.12201383],
       [0.26547767, 0.        , 0.        , 0.        , 0.11027878]])