In [1]:
import numpy as np
import random


In [2]:
# Create a NumPy Boolean array of shape (3, 4) with all elements set to True.


In [3]:
arr = np.ones((3, 4), dtype=bool)


In [4]:
arr


array([[ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])

In [5]:
# Create a NumPy Boolean array of shape (2, 3) with
# elements set to True where the value is greater than
# 5 and False where it's less than or equal to 5.


In [6]:
arr = np.random.randint(1, 11, size=(2, 3))


In [7]:
arr


array([[ 3,  6,  6],
       [ 3, 10,  4]])

In [8]:
np.where(arr > 5, True, False)


array([[False,  True,  True],
       [False,  True, False]])

In [9]:
# another solution


In [10]:
arr > 5


array([[False,  True,  True],
       [False,  True, False]])

In [11]:
# Create a NumPy Boolean array of shape (3, 3) and
# return the indices where the elements are True.


In [30]:
arr = np.random.randint(0, 2, size=(3, 3), dtype=bool)


In [31]:
arr


array([[ True, False, False],
       [ True, False, False],
       [ True,  True, False]])

In [32]:
np.where(arr)


(array([0, 1, 2, 2], dtype=int64), array([0, 0, 0, 1], dtype=int64))

In [34]:
# Create a NumPy Boolean array of shape (2, 2) and
# return the number of True elements.


In [35]:
arr = np.random.randint(0, 2, size=(2, 2), dtype=bool)


In [36]:
arr


array([[False,  True],
       [ True, False]])

In [37]:
np.sum(arr)


2

In [38]:
# another solution


In [39]:
np.count_nonzero(arr)


2

In [40]:
# Create a NumPy Boolean array of shape (2, 2) and negate all elements.


In [41]:
arr = np.random.randint(0, 2, size=(2, 2), dtype=bool)


In [42]:
arr


array([[ True, False],
       [ True, False]])

In [44]:
negate = np.logical_not(arr)


In [45]:
negate


array([[False,  True],
       [False,  True]])

In [46]:
# Given a NumPy array of shape (5, 5), create a
# Boolean array where the elements are True if they
# are odd and False if they are even.


In [47]:
arr = np.random.randint(27, 69, size=(5, 5))


In [48]:
arr


array([[58, 51, 28, 60, 53],
       [51, 42, 49, 60, 41],
       [32, 41, 60, 63, 43],
       [60, 37, 61, 38, 56],
       [31, 47, 61, 29, 42]])

In [49]:
np.where(arr % 2 == 0, False, True)


array([[False,  True, False, False,  True],
       [ True, False,  True, False,  True],
       [False,  True, False,  True,  True],
       [False,  True,  True, False, False],
       [ True,  True,  True,  True, False]])

In [50]:
# Given two Boolean arrays of the same shape (3, 3),
# compute their logical AND and OR.


In [51]:
a = np.random.randint(0, 1, size=(3, 3), dtype=bool)


In [52]:
a


array([[False, False, False],
       [False, False, False],
       [False, False, False]])

In [53]:
b = np.random.randint(0, 1, size=(3, 3), dtype=bool)


In [54]:
b


array([[False, False, False],
       [False, False, False],
       [False, False, False]])

In [55]:
logical_and_bool = np.logical_and(a, b)


In [56]:
logical_and_bool


array([[False, False, False],
       [False, False, False],
       [False, False, False]])

In [57]:
logical_or_bool = np.logical_or(a, b)


In [58]:
logical_or_bool


array([[False, False, False],
       [False, False, False],
       [False, False, False]])

In [59]:
# Given a NumPy array of shape (4, 4) and a
# Boolean array of the same shape, replace all odd elements
# in the NumPy array with 0.


In [60]:
arr = np.random.randint(17, 31, size=(4, 4))


In [61]:
arr


array([[29, 21, 18, 27],
       [20, 18, 27, 24],
       [29, 18, 17, 18],
       [29, 27, 29, 23]])

In [62]:
np.where(arr % 2 != 0, 0, arr)


array([[ 0,  0, 18,  0],
       [20, 18,  0, 24],
       [ 0, 18,  0, 18],
       [ 0,  0,  0,  0]])

In [63]:
# Given a NumPy array of shape (4, 4), create a Boolean
# array where the elements are True if the element is
# greater than the previous element and False otherwise.


In [64]:
arr = np.random.randint(52, 97, size=(4, 4))


In [65]:
arr


array([[79, 53, 86, 54],
       [90, 63, 93, 64],
       [89, 84, 93, 58],
       [60, 90, 76, 87]])

In [67]:
difference_row = np.diff(arr, axis=1)


In [68]:
difference_row


array([[-26,  33, -32],
       [-27,  30, -29],
       [ -5,   9, -35],
       [ 30, -14,  11]])

In [69]:
np.where(difference_row > 0, True, False)


array([[False,  True, False],
       [False,  True, False],
       [False,  True, False],
       [ True, False,  True]])

In [70]:
# Given a NumPy array of shape (3, 3), compute
# the mean of the elements where the Boolean array is True.


In [71]:
arr = np.random.randint(0, 2, size=(3, 3), dtype=bool)


In [72]:
arr


array([[False, False,  True],
       [False, False, False],
       [False,  True, False]])

In [76]:
np.mean(arr)


0.2222222222222222