In [1]:
# Create a NumPy array of 10 random integers between 1 and 100
# and find their square roots using the sqrt function.


In [2]:
import numpy as np
import random


In [3]:
arr = np.random.randint(1, 101, size=10)


In [4]:
arr


array([49,  2, 18, 90, 97, 40, 17, 39, 77, 96])

In [5]:
np.sqrt(arr)


array([7.        , 1.41421356, 4.24264069, 9.48683298, 9.8488578 ,
       6.32455532, 4.12310563, 6.244998  , 8.77496439, 9.79795897])

In [6]:
# Create two NumPy arrays of the same size and find their
# element-wise sum using the add function.


In [7]:
arr1 = np.random.randint(0, 11, size=10)


In [8]:
arr2 = np.random.randint(0, 11, size=10)


In [9]:
arr1


array([2, 3, 0, 1, 7, 7, 6, 2, 6, 6])

In [10]:
arr2


array([10,  0,  9,  3,  7,  4, 10,  8,  3,  2])

In [11]:
np.add(arr1, arr2)


array([12,  3,  9,  4, 14, 11, 16, 10,  9,  8])

In [12]:
# Create a NumPy array of 10 random integers between 1 and 100
# and find the absolute values of the array using the absolute function.


In [13]:
arr = np.random.randint(1, 101, size=10)


In [14]:
arr


array([15, 14, 42, 83, 47, 92, 33, 24, 41, 94])

In [15]:
np.absolute(arr)


array([15, 14, 42, 83, 47, 92, 33, 24, 41, 94])

In [16]:
# Create a NumPy array of 10 random integers between
# -50 and 50 and find the exponential values of the array
# using the exp function.


In [17]:
arr = np.random.randint(-50, 50, size=10)


In [18]:
arr


array([ 30,  13,  19,  49,  46,  32,  39,  27, -10, -44])

In [19]:
np.exp(arr)


array([1.06864746e+13, 4.42413392e+05, 1.78482301e+08, 1.90734657e+21,
       9.49611942e+19, 7.89629602e+13, 8.65934004e+16, 5.32048241e+11,
       4.53999298e-05, 7.78113224e-20])

In [20]:
# Create a NumPy array of 10 random integers between
# 1 and 100 and find the natural logarithmic values of the
# array using the log function.


In [21]:
arr = np.random.randint(1, 101, size=10)


In [22]:
arr


array([30, 44, 28, 48, 11, 57, 75, 79, 27, 95])

In [23]:
np.log(arr)


array([3.40119738, 3.78418963, 3.33220451, 3.87120101, 2.39789527,
       4.04305127, 4.31748811, 4.36944785, 3.29583687, 4.55387689])

In [24]:
# Create a NumPy array of 10 random integers between 1 and 100
# and find the sine values of the array using the sin function.
# Then, find the inverse sine values of the sine values using the
# arcsin function.


In [25]:
arr = np.random.randint(1, 101, size=10)


In [26]:
arr


array([12, 59, 56, 63, 13, 20, 65, 17, 58, 36])

In [29]:
sine_values = np.sin(arr)


In [30]:
sine_values

array([-0.53657292,  0.63673801, -0.521551  ,  0.1673557 ,  0.42016704,
        0.91294525,  0.82682868, -0.96139749,  0.99287265, -0.99177885])

In [31]:
np.arcsin(sine_values)


array([-0.56637061,  0.69026042, -0.54866776,  0.16814693,  0.43362939,
        1.15044408,  0.97344573, -1.29203673,  1.45133224, -1.44248081])

In [32]:
# Create a NumPy array of 10 random integers between
# -100 and 100 and find the sign values of the array using
# the sign function. Then, find the maximum value of the
# array where the sign is positive.


In [33]:
arr = np.random.randint(-100, 100, size=10)


In [34]:
arr


array([-82,  22,  86,   2,  12, -38,  69,  66, -73,  87])

In [35]:
sign_values = np.sign(arr)


In [36]:
sign_values


array([-1,  1,  1,  1,  1, -1,  1,  1, -1,  1])

In [37]:
np.max(arr[sign_values == 1])


87

In [38]:
# Create a NumPy array of 10 random integers between 1 and 100
# and find the cumulative sum of the array using the cumsum function.


In [39]:
arr = np.random.randint(1, 101, size=10)


In [40]:
arr


array([11, 73, 15, 10, 16, 20, 47, 97,  1, 51])

In [41]:
np.cumsum(arr)


array([ 11,  84,  99, 109, 125, 145, 192, 289, 290, 341])

In [42]:
# Create a NumPy array of 10 random integers between -100 and 100 and
# find the minimum and maximum values of the array using the clip function.
# Set the values less than -50 to -50 and the values greater than 50 to 50.


In [43]:
arr = np.random.randint(-100, 100, size=10)


In [44]:
arr


array([-77,  35,  82,  41, -32, -93,  54, -50, -18, -51])

In [45]:
arr[arr < -50] = -50


In [46]:
arr[arr > 50] = 50


In [47]:
arr


array([-50,  35,  50,  41, -32, -50,  50, -50, -18, -50])

In [48]:
#using the func clip


In [49]:
arr_clip = np.clip(arr, -50, 50)


In [50]:
arr_clip


array([-50,  35,  50,  41, -32, -50,  50, -50, -18, -50])

In [51]:
# Create a NumPy array of 10 random integers between 1 and 100 and
# find the standard deviation of the array using the std function.
# Then, find the z-score values of the array using the zscore function.


In [52]:
arr = np.random.randint(1, 101, size=10)


In [53]:
arr


array([50, 35, 36, 98, 51, 72, 87, 65, 47, 13])

In [54]:
np.std(arr)


24.270146270675834

In [56]:
z_scores = (arr - np.mean(arr)) / (np.std(arr))


In [57]:
z_scores


array([-0.22249557, -0.84053882, -0.79933593,  1.75524282, -0.18129269,
        0.68396786,  1.30201111,  0.39554768, -0.34610422, -1.74700224])

In [58]:
# Create a NumPy array of 10 random integers between 1 and 100
# and find the indices of the two largest values in the array
# using the argpartition function.


In [59]:
arr = np.random.randint(1, 101, size=10)


In [60]:
arr


array([58, 73, 12, 69, 45, 79, 25, 96, 79, 31])

In [66]:
indices = np.argpartition(arr, -2)[-2:]


In [67]:
indices

array([8, 7], dtype=int64)

In [68]:
# Create a NumPy array of 10 random integers between -100 and 100
# and find the Pearson correlation coefficient between the
# values of the array and their index positions using
# the corrcoef function.


In [69]:
arr = np.random.randint(-100, 100, size=10)


In [70]:
arr


array([ -3, -56,  16, -32, -63,  28, -51, -33,  77, -19])

In [71]:
corr_coefficient = np.corrcoef(arr, np.arange(len(arr)))[0, 1]


In [72]:
corr_coefficient


0.2410111038652094

In [73]:
# Create a NumPy array of 10 random integers between 1 and 100 and
# find the values in the array that are greater than the mean of
# the array using the masked arrays feature.


In [74]:
arr = np.random.randint(1, 101, size=10)


In [75]:
arr


array([11, 50, 21, 68, 94, 78, 31, 16, 57, 94])

In [76]:
arr_mask = np.ma.masked_less_equal(arr, np.mean(arr))


In [77]:
arr_mask


masked_array(data=[--, --, --, 68, 94, 78, --, --, 57, 94],
             mask=[ True,  True,  True, False, False, False,  True,  True,
                   False, False],
       fill_value=999999)

In [78]:
arr_mask.compressed()


array([68, 94, 78, 57, 94])

In [79]:
# Create a NumPy array of 10 random integers between -100 and 100
# and find the values in the array that are within two standard
# deviations of the mean of the array using the where function.


In [80]:
arr = np.random.randint(-100, 100, size=10)


In [81]:
arr


array([ 29,  67,  66,  99,  99,   3,  27,  78, -37,  77])

In [82]:
arr[np.where(np.abs(arr - np.mean(arr)) < 2 * np.std(arr))]


array([29, 67, 66, 99, 99,  3, 27, 78, 77])

In [83]:
# Create a NumPy array of 10 random integers between 1 and 100 and
# find the mode of the array using the unique function and the
# bincount function.


In [84]:
arr = np.random.randint(1, 101, size=10)


In [85]:
arr


array([ 51,  48, 100,  94,  32,  63,  95,  50,  57,  12])

In [86]:
unique_values, counts = np.unique(arr, return_counts=True)


In [87]:
unique_values[np.argmax(counts)]


12