In [1]:
# Create a new array with only the positive values from
# the given array using NumPy.


In [2]:
import numpy as np
import random


In [3]:
rng = np.random.default_rng(12345)


In [4]:
arr = rng.standard_normal(10)


In [5]:
arr


array([-1.42382504,  1.26372846, -0.87066174, -0.25917323, -0.07534331,
       -0.74088465, -1.3677927 ,  0.6488928 ,  0.36105811, -1.95286306])

In [6]:
arr_positive = np.where(arr > 0)


In [8]:
new_arr = arr[arr_positive]  # or new_arr = arr[arr > 0]


In [9]:
new_arr


array([1.26372846, 0.6488928 , 0.36105811])

In [10]:
# Create a new array with only the even values from the given array using NumPy.


In [12]:
arr = np.random.randint(13, 59, size=10)


In [13]:
arr


array([13, 35, 23, 27, 16, 45, 54, 19, 30, 20])

In [14]:
arr[np.where(arr % 2 == 0)]


array([16, 54, 30, 20])

In [16]:
# Create a new array with only the values that are both positive
# and even from the given array using NumPy.


In [17]:
arr = np.random.randint(-23, 57, size=10)


In [18]:
arr


array([  2,  -5, -21,  38,  52,  18,  15,   9,  -3,  49])

In [22]:
arr[np.where((arr > 0) & (arr % 2 == 0))]


array([ 2, 38, 52, 18])

In [23]:
# Replace all the negative values in the given array with 0 using NumPy.


In [26]:
arr = np.random.randint(-21, 63, size=10)


In [27]:
arr


array([  3,  21,  17, -10,  38,  17,   2,  35,  14, -19])

In [29]:
np.where(arr < 0, 0, arr)


array([ 3, 21, 17,  0, 38, 17,  2, 35, 14,  0])

In [30]:
# Create a new array that contains the square of all the
# even values in the given array using NumPy.


In [31]:
arr = np.random.randint(27, 74, size=10)


In [32]:
arr


array([53, 29, 73, 27, 54, 70, 33, 54, 43, 56])

In [33]:
np.where(arr % 2 == 0, arr ** 2, arr)


array([  53,   29,   73,   27, 2916, 4900,   33, 2916,   43, 3136])

In [34]:
# Given two arrays a and b of the same length, create a new
# array with elements from a if they are greater than or equal
# to the corresponding element in b, and elements from b otherwise.


In [35]:
a = np.random.randint(19, 57, size=10)


In [36]:
a


array([50, 45, 54, 22, 34, 20, 32, 55, 56, 29])

In [37]:
b = np.random.randint(29, 73, size=10)


In [38]:
b


array([63, 60, 55, 49, 29, 42, 62, 44, 69, 41])

In [39]:
np.where(a >= b, a, b)


array([63, 60, 55, 49, 34, 42, 62, 55, 69, 41])

In [40]:
# Given a 2D array, replace all values in each row that are
# greater than the median of that row with the median value.


In [41]:
arr = np.random.randint(27, 83, size=(4, 4))


In [42]:
arr


array([[82, 33, 51, 49],
       [39, 35, 49, 57],
       [37, 66, 32, 73],
       [42, 60, 49, 27]])

In [43]:
median = np.median(arr, axis=1, keepdims=True)


In [45]:
median


array([[50. ],
       [44. ],
       [51.5],
       [45.5]])

In [47]:
np.where(arr > median, median, arr)


array([[50. , 33. , 50. , 49. ],
       [39. , 35. , 44. , 44. ],
       [37. , 51.5, 32. , 51.5],
       [42. , 45.5, 45.5, 27. ]])

In [48]:
# Given a 2D array of size m x n, find the indices of the maximum value in each row.


In [49]:
m = 3
n = 4


In [65]:
arr = np.random.randint(33, 89, size=(m, n))


In [66]:
arr


array([[38, 69, 67, 73],
       [64, 50, 48, 85],
       [73, 77, 34, 73]])

In [67]:
max_indices = np.argmax(arr, axis=1)


In [68]:
max_indices


array([3, 3, 1], dtype=int64)

In [69]:
# Given two 1D arrays a and b, create a new array that
# contains the sum of elements from a and b where the
# element from a is less than 5 and the element from b is
# greater than 5.


In [82]:
a = np.random.randint(1, 10, size=10)


In [83]:
a


array([5, 2, 7, 9, 1, 7, 3, 3, 5, 2])

In [84]:
b = np.random.randint(1, 10, size=10)


In [85]:
b


array([7, 8, 2, 6, 8, 1, 3, 7, 9, 2])

In [86]:
np.where(((a < 5) & (b > 5)), a + b, 0)


array([ 0, 10,  0,  0,  9,  0,  0, 10,  0,  0])

In [87]:
# Given a 2D array of size m x n, create a new array where
# each element is the sum of the four neighboring elements
# (top, bottom, left, right).


In [118]:
arr = np.arange(1, 10).reshape(3, 3)


In [119]:
arr


array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [120]:
top = np.roll(arr, 1, axis=0)


In [121]:
top


array([[7, 8, 9],
       [1, 2, 3],
       [4, 5, 6]])

In [122]:
bottom = np.roll(arr, -1, axis=0)


In [123]:
bottom


array([[4, 5, 6],
       [7, 8, 9],
       [1, 2, 3]])

In [124]:
left = np.roll(arr, 1, axis=1)


In [125]:
left


array([[3, 1, 2],
       [6, 4, 5],
       [9, 7, 8]])

In [126]:
right = np.roll(arr, -1, axis=1)


In [127]:
right


array([[2, 3, 1],
       [5, 6, 4],
       [8, 9, 7]])

In [128]:
sum_all_positions = top + bottom + left + right


In [129]:
sum_all_positions


array([[16, 17, 18],
       [19, 20, 21],
       [22, 23, 24]])

In [130]:
# get the middle
sum_all_positions[1, 1]


20

In [131]:
# Given a 2D array arr of size m x n, replace all values that
# are less than the mean of their row and column with the mean of the row and column.


In [193]:
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])


In [194]:
arr


array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [195]:
row_means = np.mean(arr, axis=1, keepdims=True)


In [196]:
col_means = np.mean(arr, axis=0, keepdims=True)


In [197]:
row_means


array([[2.],
       [5.],
       [8.]])

In [198]:
col_means


array([[4., 5., 6.]])

In [201]:
means = np.mean(np.concatenate([row_means, col_means.T], axis=1))



In [202]:
means


5.0

In [203]:
mask = arr < means


In [206]:
arr[mask] = means


In [207]:
arr

array([[5, 5, 5],
       [5, 5, 6],
       [7, 8, 9]])

In [208]:
# Given a 2D array arr of size m x n and an array mask of the
# same size, replace all values in arr where the corresponding
# value in mask is zero with the mean of the row in arr.


In [209]:
arr = np.arange(1, 10).reshape(3, 3)


In [210]:
arr


array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [214]:
mask = np.random.randint(0, 2, size=(3, 3))


In [215]:
mask


array([[1, 0, 1],
       [0, 1, 0],
       [1, 0, 1]])

In [220]:
mean_row = np.mean(arr, axis=1, keepdims=True)


In [221]:
mean_row


array([[2.],
       [5.],
       [8.]])

In [225]:
np.where(mask == 0, mean_row, arr)


array([[1., 2., 3.],
       [5., 5., 5.],
       [7., 8., 9.]])

In [226]:
# Given a 1D array arr, find the largest consecutive subsequence such that
# the difference between each pair of adjacent elements is less than
# or equal to 2.


In [242]:
arr = np.array([2, 3, 5, 8, 10, 11, 12, 14, 16, 19])


In [243]:
arr


array([ 2,  3,  5,  8, 10, 11, 12, 14, 16, 19])

In [244]:
difference = np.diff(arr)


In [265]:
difference


array([1, 2, 3, 2, 1, 1, 2, 2, 3])

In [286]:
max_diff = max(difference)


In [291]:
max_index = np.where(np.diff(arr) <= 2)


In [292]:
arr2 = arr[max_index]


In [293]:
arr2


array([ 2,  3,  8, 10, 11, 12, 14])

In [309]:
arr2[-2:]


array([12, 14])

In [310]:
# Given a 2D array arr of size m x n, create a new 2D array with
# elements that are the maximum of all elements in the same row or column.

In [311]:
arr = np.arange(1, 10).reshape(3, 3)


In [312]:
arr


array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [313]:
max_row = np.max(arr, axis=1, keepdims=True)


In [314]:
max_col = np.max(arr, axis=0, keepdims=True)


In [315]:
max_row


array([[3],
       [6],
       [9]])

In [316]:
max_col


array([[7, 8, 9]])

In [368]:
maxes = np.max(max_row, axis=1)


In [369]:
maxes


array([3, 6, 9])

In [381]:
np.tile(maxes, (arr.shape[0], 1))

array([[3, 6, 9],
       [3, 6, 9],
       [3, 6, 9]])